(ns twitter-clj.application.port.service)

(defprotocol UserService
  (login [service user-id])
  (logout [service session-id])
  (logout-all [service user-id])
  (new-user? [service email])
  (user-exists? [service user-id])
  (password-match? [service user-id password])
  (create-user [service name email username password])
  (get-user-by-id [service user-id])
  (follow [service follower-id followed-id])
  (unfollow [service follower-id followed-id])
  (get-following [service follower-id])
  (get-followers [service followed-id]))

(defprotocol TweetService
  (tweet [service user-id text])
  (get-tweet-by-id [service tweet-id])
  (get-tweets-by-user [service user-id])
  (get-tweets-with-hashtag [service hashtag])
  (reply [service user-id text source-tweet-id])
  (get-replies-by-tweet-id [service source-tweet-id])
  (retweet [service user-id source-tweet-id])
  (retweet-with-comment [service user-id comment source-tweet-id])
  (get-retweet-by-id [service retweet-id])
  (get-retweets-by-tweet-id [service source-tweet-id])
  (like [service user-id tweet-id])
  (unlike [service user-id tweet-id])
  (get-feed [service user-id limit offset]))
